# Generated by Django 5.2.1 on 2025-06-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
    ]
