# Generated by Django 5.2.1 on 2025-05-11 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cuentas_cobrar', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='venta',
        ),
        migrations.AlterField(
            model_name='cuota',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('mensual', 'Mensual'), ('personalizada', 'Personalizada')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='ventas.venta')),
            ],
        ),
        migrations.AddField(
            model_name='cuota',
            name='credito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='cuentas_cobrar.credito'),
        ),
    ]
