# Generated by Django 5.2.1 on 2025-05-10 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.factura')),
            ],
        ),
    ]
