# Generated by Django 5.2.1 on 2025-06-22 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0003_alter_producto_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('mensual', 'Mensual'), ('personalizada', 'Personalizada')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('dias_vencimiento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vence', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='ventas.creditoventa')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('moneda', models.CharField(default='Guaraní', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('modalidad', models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
        ),
        migrations.AddField(
            model_name='creditoventa',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='ventas.venta'),
        ),
    ]
