# Generated by Django 5.2.1 on 2025-06-23 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotaventa',
            old_name='monto',
            new_name='importe',
        ),
    ]
