# Generated by Django 5.2.1 on 2025-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_monto_cuotaventa_importe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='observacion',
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
