# Generated by Django 5.2.1 on 2025-05-13 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('mensual', 'Mensual'), ('personalizada', 'Personalizada')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('dias_vencimiento', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vence', models.DateField()),
                ('cobrado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='facturacion.credito')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('moneda', models.CharField(default='Guaraní', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('modalidad', models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='facturacion.factura'),
        ),
    ]
