# Generated by Django 5.2.1 on 2025-06-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='cantidad_cuotas',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='dias_vencimiento',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='credito',
            name='plazo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creditos.plazo'),
            preserve_default=False,
        ),
    ]
