# Generated by Django 5.2.1 on 2025-05-15 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
        migrations.AddField(
            model_name='compra',
            name='modalidad',
            field=models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=2),
        ),
        migrations.AddField(
            model_name='compra',
            name='moneda',
            field=models.CharField(default='Guaraní', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
