# Generated by Django 5.2.1 on 2025-05-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_producto'),
        ('proveedores', '0002_proveedor_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
