# Generated by Django 5.2.1 on 2025-05-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_proveedor_delete_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocompra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
