# Generated by Django 5.2.1 on 2025-05-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_pagocompra_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
