# Generated by Django 5.2.1 on 2025-05-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_compra_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
    ]
