# Generated by Django 5.2.1 on 2025-06-05 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CreditoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('modalidad', models.CharField(choices=[('mensual', 'Mensual'), ('personalizada', 'Personalizada')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('dias_vencimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vence', models.DateField()),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='compras.creditocompra')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.DeleteModel(
            name='PagoCompra',
        ),
    ]
