# Generated by Django 5.2.1 on 2025-06-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_compra_observacion_alter_compra_total_creditocompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='observacion',
        ),
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
