# Generated by Django 5.2.1 on 2025-06-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_cuotas', models.PositiveIntegerField()),
                ('es_irregular', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Plazos',
            },
        ),
        migrations.CreateModel(
            name='TipoPlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePlazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('dias_vencimiento', models.PositiveIntegerField()),
                ('plazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='creditos.plazo')),
            ],
            options={
                'ordering': ['plazo', 'numero_cuota'],
            },
        ),
        migrations.AddField(
            model_name='plazo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creditos.tipoplazo'),
        ),
    ]
