# Generated by Django 5.2.1 on 2025-05-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
